name: Build and Deploy Zola

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          ZOLA_VERSION=0.21.0
          curl -L https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz
          sudo mv zola /usr/local/bin

      - name: Build site
        run: zola build

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "public/*"
          target: "/var/www/html"  # Adjust to your hosting path
